[package]
name = "lib_transferwise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macros_create_app = {path="../macros_create_app"}
